# Generated by Django 5.2 on 2025-04-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeingAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
