# Generated by Django 5.2 on 2025-04-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeingAI', '0002_remove_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellbeingAI.course')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellbeingAI.studentprofile')),
            ],
        ),
    ]
